# Generated by Django 4.0.6 on 2022-09-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_chapter_homework_homeworkquestion_quiz_quizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChapterTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.chapter')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.title')),
            ],
        ),
    ]
